DROP TABLE IF EXISTS PURCHASE;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID IDENTITY,
    USER_ID VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PURCHASE (
    PURCHASE_ID IDENTITY,
    PURCHASE_AMOUNT DECIMAL(12,2) NOT NULL,
    PURCHASE_DATE TIMESTAMP NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    CONSTRAINT PURCHASE2CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

INSERT INTO CUSTOMER (USER_ID, FIRST_NAME, LAST_NAME) VALUES ( 'coberg', 'Christopher', 'Oberg' );
INSERT INTO CUSTOMER (USER_ID, FIRST_NAME, LAST_NAME) VALUES ( 'ebridg', 'Ezra', 'Bridger' );
INSERT INTO CUSTOMER (USER_ID, FIRST_NAME, LAST_NAME) VALUES ( 'golaak', 'Laa''ki', 'Goblin' );
INSERT INTO CUSTOMER (USER_ID, FIRST_NAME, LAST_NAME) VALUES ( 'jsmith', 'John', 'Smith' );


INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 250.00, PARSEDATETIME('2020-10-30', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'ebridg') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 200.00, PARSEDATETIME('2021-05-30', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'ebridg') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 350.00, PARSEDATETIME('2021-06-01 12:00:00', 'yyyy-MM-dd HH:mm:ss'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'coberg') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 350.00, PARSEDATETIME('2021-07-01 12:00:00', 'yyyy-MM-dd HH:mm:ss'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'coberg') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 350.00, PARSEDATETIME('2021-08-01 12:00:00', 'yyyy-MM-dd HH:mm:ss'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'coberg') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 5000.00, PARSEDATETIME('2021-08-15', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'golaak') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 350.00, PARSEDATETIME('2021-09-01 12:00:00', 'yyyy-MM-dd HH:mm:ss'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'coberg') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 20.00, PARSEDATETIME('2021-09-26', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'jsmith') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 10.00, PARSEDATETIME('2021-09-26', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'jsmith') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 30.00, PARSEDATETIME('2021-09-27', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'jsmith') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 80.00, PARSEDATETIME('2021-09-28', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'jsmith') );
INSERT INTO PURCHASE (PURCHASE_AMOUNT, PURCHASE_DATE, CUSTOMER_ID) VALUES ( 250.00, PARSEDATETIME('2021-09-30', 'yyyy-MM-dd'), (SELECT CUSTOMER_ID FROM CUSTOMER WHERE USER_ID = 'ebridg') );
